import Head from "next/head";
import { useEffect, useState } from "react";
import About from "../components/About";
import Contact from "../components/Contact";
import Header from "../components/Header";
import Layout from "../components/Layout";
import Modal from "../components/Modal";
import ProjectSummary from "../components/ProjectSummaryHome";
import Skills from "../components/Skills";

export default function Home() {
  const [projectNameSelected, setProjectNameSelected] = useState(undefined);
  const [openModal, setOpenModal] = useState(false);

  const openProjectModal = (projectName) => {
    setProjectNameSelected(projectName);
    setOpenModal(true);
  };

  useEffect(() => {
    if (openModal) {
      document.body.style.overflow = "hidden";
    } else [(document.body.style.overflow = "unset")];
  }, [openModal]);

  return (
    <>
      <Head>
        <title>Sajmon Nowak Webdeveloper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <Header />
          <Skills />
          <ProjectSummary openProjectModal={openProjectModal} />
          <Contact />
          <Modal
            projectName={projectNameSelected}
            setOpenModal={setOpenModal}
            openModal={openModal}
          />
        </main>
      </Layout>
    </>
  );
}
